# Generated by Django 5.1.7 on 2025-03-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='locked_until',
        ),
    ]
